name: news_app
description: "App to show news based on newsapi org"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  network_image_mock: ^2.0.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
